### ISSUE TITLE
Music plays on top of itself when enter is pressed twice

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#5] opened 2015-02-13 17:49 UTC
If you update your code and want to listen to the updated version of it, the intuitive thing to do is just to press enter again, not to press stop and then start. Perhaps we could use live loops instead of loops?

**Comment by tjvr** [comment] 2015-02-15 19:10
I thought we were using live loops...

**Comment by isaac-dunn** [comment] 2015-02-15 19:17
Oh yes, you're right. I seem to remember the playing over itself being a issue though, which I assumed wouldn't the best case if we were using live loops? I thought the whole point of live loops was that submitting the code again updated the loop rather than just playing it - are we using them wrong, or am I mistaken and this problem doesn't happen?

**Comment by tjvr** [comment] 2015-02-15 20:59
> am I mistaken and this problem doesn't happen?

No idea. If you can't reproduce this, I guess you should close the issue...

**Comment by isaac-dunn** [comment] 2015-02-15 22:15
I haven't tried, I don't have a machine with our app running on it.

**Comment by LauraneS** [comment] 2015-02-16 23:50
I don't think this was an issue. You could just press enter without stopping whatever was playing and it was updated I think

**Closed as completed** 2015-02-17 00:06 UTC
Labels: enhancement
